### ISSUE TITLE
Possible false positives

### ISSUE THREAD

**Issue by whyboris** [nadeesha/ts-prune#1]
Excellent work!

I ran the tool against our *Angular* production code and found 13 genuine unused exports 👏 

Thank you 🙇 

There were some false positives on the list. For example:
`ComposeModule @ [our-project]/src/app/compose/compose.module.ts:59`

But it _is_ used in our `app-rounting.module.ts` like this:
```
const appRoutes: Routes = [
  { path: 'compose',
    loadChildren: 'app/compose/compose.module#ComposeModule' }
```

It's likely more trouble than it's worth trying to catch edge cases like this (it took me seconds to confirm that indeed the import is getting used with _Find in Files_), but wanted to share.

**Comment by nadeesha** [comment]
@whyboris Thanks for reporting this. Glad you found it useful.

I believe it happens because this is a dynamic import. It would indeed be somewhat hard to account for this scenario.

One recommendation I have is to ignore the identifiers that may be dynamically imported using `grep`. I've just added that to the [FAQ](https://github.com/nadeesha/ts-prune/blob/master/README.md#how-do-i-ignore-a-specific-identifier) now.
