### ISSUE TITLE
False positive results with imports via `paths` alias

### ISSUE THREAD

**Issue by nadeesha** [nadeesha/ts-prune#139]
### Discussed in https://github.com/nadeesha/ts-prune/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **jtbandes** June  9, 2021</sup>
Hello @nadeesha! I just tried using ts-prune for the first time on [this repository](https://github.com/foxglove/studio) and I'm confused by the results, because many/most of them seem to be false positives.

The repo is a monorepo with several packages. This is the command I ran to try out ts-prune on the biggest package ([here's the tsconfig.json](https://github.com/foxglove/studio/blob/7142d5e1c810cfc427fe2d2a6a860ed81424f132/packages/studio-base/tsconfig.json)):

```
yarn dlx ts-prune -p packages/studio-base/tsconfig.json
```

The results look like this:
```
packages/studio-base/src/App.tsx:31 - default
packages/studio-base/src/AppSetting.ts:5 - AppSetting
packages/studio-base/src/index.ts:11 - App
packages/studio-base/src/index.ts:12 - NetworkInterface
packages/studio-base/src/index.ts:12 - OsContext
....a bunch more from index.ts....
packages/studio-base/src/OsContextSingleton.ts:13 - default
packages/studio-base/src/Workspace.tsx:142 - default
....lots more results....
```

For example, the first result is the [default export of `App.tsx`](https://github.com/foxglove/studio/blob/7142d5e1c810cfc427fe2d2a6a860ed81424f132/packages/studio-base/src/App.tsx#L31). This is [re-exported from `index.tsx`](https://github.com/foxglove/studio/blob/7142d5e1c810cfc427fe2d2a6a860ed81424f132/packages/studio-base/src/index.ts#L11), so I wouldn't expect it to be considered unused.

For another example let's look at the [default export from `OsContextSingleton.ts`](https://github.com/foxglove/studio/blob/7142d5e1c810cfc427fe2d2a6a860ed81424f132/packages/studio-base/src/OsContextSingleton.ts#L13) — this is imported as `import OsContextSingleton from "@foxglove/studio-base/OsContextSingleton";` in several places ([here's one example](https://github.com/foxglove/studio/blob/7142d5e1c810cfc427fe2d2a6a860ed81424f132/packages/studio-base/src/components/Preferences.tsx#L20)).

Is it our [`paths` setting](https://github.com/foxglove/studio/blob/7142d5e1c810cfc427fe2d2a6a860ed81424f132/packages/studio-base/tsconfig.json#L10) that's throwing off ts-prune? Or am I doing something else wrong?

Thanks for your help! This seems like a great project and it would be awesome if it worked for us.</div>

**Comment by nadeesha** [comment]
@jtbandes @connorads Apologies for the radio silence on this. Since the Q&A format is not so great when I'm trying to get to the root cause, and since I can't give you an obvious answer, let's move the discussion here.

I don't think you're doing something obviously wrong. 

Am I correct in assuming that, some imports from `@foxglove/studio-base/...` work and some don't?

**Comment by jtbandes** [comment]
> Am I correct in assuming that, some imports from `@foxglove/studio-base/...` work and some don't?

Not sure I understand the question — do you mean to ask whether ts-prune is returning some false positives and some true positives?

I just tried running it again because it's been a while since I originally tried, and some of our package structure / tsconfig has been changed since then. Some of the false positives I previously mentioned are gone – for example the App and OsContextSingleton exports. 👍 

Otherwise:

- The `index.ts` exports are all considered unused. It may be true that they aren't imported inside this package, but this file defines the package's public API (and we do have `"main": "src/index"` in package.json to indicate this), so I don't think they should be considered unused.

- There are some entries that need to be ignored — this is probably expected. For example, the following exports for Storybook (using the [Component Story Format](https://storybook.js.org/docs/react/api/csf)). It's true that our own code doesn't explicitly import them, and I can understand why ts-prune shows them, but I will need to filter these out.

   ```
   packages/studio-base/src/components/NotificationModal.stories.tsx:24 - default
   packages/studio-base/src/components/NotificationModal.stories.tsx:28 - ErrorModal
   packages/studio-base/src/components/NotificationModal.stories.tsx:44 - Warning
   packages/studio-base/src/components/NotificationModal.stories.tsx:60 - ErrorWithoutDetails
   packages/studio-base/src/components/NotificationModal.stories.tsx:76 - ErrorWithJsxElementDetails
   ```

- Some entries are shown from other packages in our monorepo, which is surprising because they shouldn't be picked up by this tsconfig. These are specified as workspace dependencies, for example studio-base/package.json includes `"@foxglove/hooks": "workspace:*"`.
   ```
   packages/hooks/src/useRethrow.ts:18 - default
   packages/hooks/src/useShallowMemo.ts:8 - default
   packages/hooks/src/useVisibilityState.ts:7 - default
   packages/den/async/LazilyInitialized.ts:9 - default
   packages/den/async/MutexLocked.ts:13 - default
   ```

- Otherwise, I see a lot of correct results – code that is actually unused and can be deleted 👍
   ```
   packages/studio-base/src/components/Progress.tsx:66 - default
   ```

**Comment by nadeesha** [comment]
> Not sure I understand the question — do you mean to ask whether ts-prune is returning some false positives and some true positives?

Yes.

> The index.ts exports are all considered unused. It may be true that they aren't imported inside this package, but this file defines the package's public API (and we do have "main": "src/index" in package.json to indicate this), so I don't think they should be considered unused.

Unfortunately, ts-prune is not `packageJson.main` aware. We might need to account for this property to fix this properly.

> There are some entries that need to be ignored — this is probably expected. For example, the following exports for Storybook (using the Component Story Format). It's true that our own code doesn't explicitly import them, and I can understand why ts-prune shows them, but I will need to filter these out.

Yes. It's not storybook aware. Most users just ignore the storybook dirs.

> Otherwise, I see a lot of correct results – code that is actually unused and can be deleted

Thanks for the feedback! 🙌
