### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by OliverJAsh** [nadeesha/ts-prune#2]
Hi @nadeesha 👋 

Thanks for making the [gist](https://gist.github.com/dsherret/0bae87310ce24866ae22425af80a9864) into a CLI!

One thing I've been wondering is how to improve the performance.

On one of my large TS projects, this script takes up to 4 minutes to run on my machine.

@dsherret Do you have any ideas how to make this faster? Is there something with ts-morph we should be doing differently?

**Comment by dsherret** [comment]
Thanks for tagging me in this @OliverJAsh!

One rather large performance improvement would be to use `#findReferences()` instead of `#findReferencesAsNodes()`. Basically it would be changing this check...

```ts
node.findReferencesAsNodes().filter(n => n.getSourceFile() !== file).length > 0
```

...to something like...

```ts
node.findReferences().some(referencedSymbol => referencedSymbol.getReferences().some(reference => reference.getSourceFile() !== file))
```

Using `some` instead of filtering and getting the length will help too.

The reason this will be faster is `findReferencesAsNodes()` internally uses `findReferences()`, iterates through all the results, and finally traverses the source file ASTs to find the nodes.

Overall though, a solution that doesn't use the language service (which `findReferences` and `findReferencesAsNodes` internally does) would be fastest because it could stop searching once it finds a single reference. I can look into it more later, but a hint on how to do it would be to take a look at [this file](https://github.com/microsoft/TypeScript/blob/0f6f3b79b5ddbd3be2a0fc6ed63371302faf6ba7/src/services/findAllReferences.ts) in the compiler api. I'm not sure if everything is exposed to do it though (my familiarity with using symbols in the compiler api is not so great).

**Comment by nadeesha** [comment]
Hi, @OliverJAsh and @dsherret - thanks for your input on this. I'll take a shot at `findReferencesAsNodes` -> `findReferences` when I have some time to work on this again. Hopefully very soon.

I've looked at the typescript source @dsherret suggested, and it seems like it won't be trivial to short circuit the `getImportSearches()` -  at least from my initial exploration. Happy to look at it again if you have better suggestions.

**Comment by Simon-Tang** [comment]
Hi @nadeesha and thanks for making this tool! It certainly works... although on my large codebase it's still running after maybe 45 minutes. I wonder if there's some sort of memoization that could be employed here, or some other optimization?

**Comment by dsherret** [comment]
Another possible performance improvement is there is a graph that's lazily built internally in ts-morph that keeps track of connections between source files (the connections can be retrieved with `sourceFile.getReferencingSourceFiles()` or `sourceFile.getReferencingNodesInOtherSourceFiles()`). Basically, it should be possible to analyze all the exports from the source file, then use `sourceFile.getReferencingNodesInOtherSourceFiles()` to analyze those nodes to see if the export is used in the file. That should be even faster, but a bit more complicated to implement.

**Comment by OliverJAsh** [comment]
Random note: VS Code has a lenses feature which shows inline references above each declaration. They seem to appear as soon as I open a source file. I wonder how they make that work so fast…

**Comment by nadeesha** [comment]
Thanks for the feedback!

I'll put in some time on it this week to see whether I can do some of these optimisations.

I think the starting point is to have an integration test that generates a mock Typescript project with a lot of exports to be large enough to get a benchmark on things first.

**Comment by nadeesha** [comment]
Just an update that I started on this at #6

**Comment by nadeesha** [comment]
The performance improvements are now published with v0.1.1.

In the end, I followed @dsherret's advice on leveraging `getReferencingNodesInOtherSourceFiles()`. That allowed to analyze each file on its own. It should hopefully be faster and consume less memory now.

Would be keen to hear it fares with your projects now. Especially @Simon-Tang with the memory running out issues.

Thank you all for your valuable feedback. 🙏

**Comment by Simon-Tang** [comment]
Yep @nadeesha, your fix took the tool from > 45 minutes (and memory running out) to 12 seconds. 🎉  Thanks for making this!

**Comment by OliverJAsh** [comment]
Down to 27s for me, much better. Amazing ❤️

**Comment by nadeesha** [comment]
Thank you @Simon-Tang and @OliverJAsh for the encouraging feedback. Closing this with the fix attributed to #6.

**Comment by dsherret** [comment]
Nice!

Worth noting that I think it will only work now with import declarations. Does it work with transitively exported declarations (ex. `export { Something } from "./otherFile";`)? Also, what about dynamic imports (ex. `import("./someFile").then(obj => ...)`? If not, I think that might just be something to improve on in the future.

I think probably import equals declarations (ex. `import something = require("./someWhere");`) is not worth implementing, but maybe it is.

**Comment by nadeesha** [comment]
Transitive exports and dynamic imports do not work, yes. Maybe this is a point of improvement. Thanks @dsherret.
