### ISSUE TITLE
Doesn't handle dynamic imports

### ISSUE THREAD

**Issue by turadg** [nadeesha/ts-prune#29]
Web apps often lazy load modules to defer requests. ts-prune doesn't detect these imports.

E.g.,
```
const module = await import(/* webpackChunkName: 'user_prompts_lazy' */ 'user_prompts');
```

**Comment by nadeesha** [comment]
Thanks @turadg. Unfortunately, there's no good way I see of handling this. I'll accept a PR if you don't mind digging around.

**Comment by OliverJAsh** [comment]
Did the original version support this? (The one that came from [the gist](https://gist.github.com/dsherret/0bae87310ce24866ae22425af80a9864)?)

After upgrading ts-prune, I have a huge number of errors relating to module `default` exports:

```
default @ /client/uploader/components/Form/components/Dropbox/Dropbox.tsx
default @ /client/uploader/components/Form/components/FormValidFileErrors/FormValidFileErrors.tsx
default @ /client/uploader/components/Form/components/LimitWarning/LimitWarning.tsx
default @ /client/uploader/components/FormInvalidFileList/components/AllGroupsList/AllGroupsList.tsx
default @ /client/uploader/components/FormValidFileGrid/components/FormValidFile/FormValidFile.tsx
default @ /client/uploader/components/PublishingComplete/components/AllFailed/AllFailed.tsx
default @ /client/uploader/components/PublishingComplete/components/AllSucceeded/AllSucceeded.tsx
default @ /client/uploader/components/PublishingComplete/components/Content/Content.tsx
default @ /client/uploader/components/PublishingComplete/components/RollbackFailuresButton/RollbackFailuresButton.tsx
default @ /client/uploader/components/PublishingComplete/components/SomeFailed/SomeFailed.tsx
default @ /app/components/Masonry/components/MasonryPhoto/components/PhotoOverlay/PhotoOverlay.tsx
```

I never had these false positives in v0.0.7. 🤔 

I can only guess this is because these modules are transitive dependencies of dynamic imports.

**Comment by nadeesha** [comment]
Yes, it would have. Unfortunately, the version in the gist uses APIs that yield poor performance. Right now, I've implemented heuristically matching things to make it fast. I'll need to add this case to the matcher.

**Comment by eltonio450** [comment]
hi there,

any idea where to start to find a solution on this :) ?

thank you !

**Comment by nadeesha** [comment]
It seems that `ts-morph` (the library that this library uses underneath) doesn't return `async` imports for `getImportDeclarations()` method. I don't have enough time right now dig into the issue, or try to find an alternative.

One possible workaround would be to `// ts-prune-ignore-next` on async imports, but that'd be pretty cumbersome in a large project.

**Comment by eltonio450** [comment]
ok I'll have a look, thanks :)

**Comment by koddsson** [comment]
> Unfortunately, the version in the gist uses APIs that yield poor performance.

If you are looking for user input then I'd take poor performance over not being able to use the app at all since I'm using dynamic imports.

The gist runs for ~16s going over ~73500 files on my local machine. I'm planning to only run it in CI so I don't mind the time it takes. I realize that might be the use case for everyone though.

**Comment by nadeesha** [comment]
@koddsson You're welcome to try and make the gist perform well. Maybe the APIs had changed to the point that the gist is fast again. For context, please see #2.

**Comment by phiresky** [comment]
pr to fix this: https://github.com/nadeesha/ts-prune/pull/68
