### ISSUE TITLE
Is it possible to exclude results that are used within the same file?

### ISSUE THREAD

**Issue by mildfuzz** [nadeesha/ts-prune#38]
I have a lot of what I would consider to be false positives. A method is not being used as in import anywhere, but it being used within the same file. Is there a way to filter these out?

**Comment by nadeesha** [comment]
Thanks for the issue @mildfuzz. Although you might have a legitimate reason to export something that's not being imported elsewhere, the objective of this package is to find unused imports. If you feel like this is a worthwhile addition, I'm keen to hear your reasons.

**Comment by emlai** [comment]
I think most users (including me) want to use ts-prune to find dead code. Exported entities used within the same file are not dead code, so we don't care about those cases.

In my opinion, detecting redundant usages of the `export` keyword doesn't add much value because those cases rarely indicate bugs (in my experience). It just means we need to manually remove the `export` keyword in those cases, which is a bit cumbersome. An automatic fix mode as outlined in #23 would make it less of a problem though.

**Comment by nadeesha** [comment]
I'm more than happy to find a way to incorporate this feature if there's enough interest.

**Comment by nadeesha** [comment]
Since I'm not sure we have a viable use-case that might benefit from implementing this, I'm closing it for now.

**Comment by thehappycoder** [comment]
I'd like this feature. It's a shame this issue got closed.

**Comment by JustFly1984** [comment]
just remove `export`, if it is not imported anywhere.

**Comment by nadeesha** [comment]
I'd second what @JustFly1984 said. If you're not using it anywhere, I'm not sure why the export keyword should be used.

**Comment by mildfuzz** [comment]
Just like functions and variables stop being used. They get superseded. The
export was useful, now it is not. Pretty common on large codebases in my
experience.

**Comment by emlai** [comment]
In a large enough codebase, there can be hundreds or thousands of unnecessary exports. Going through all of them manually (due to lack of automatic fixing, #23) to check which ones can safely be removed is not always viable.

**Comment by danvk** [comment]
@nadeesha is there an alternative tool you'd recommend for finding unused code?

**Comment by nadeesha** [comment]
@danvk Unfortunately not. That seems to be a much bigger problem :)

**Comment by nadeesha** [comment]
@mildfuzz @emlai I want to bring closure to this issue since it seems I might have closed it a bit prematurely.

The goal of this package is to find unused exports. If the export is used within the same file, there's no reason to export it, IMHO. But I can see that it could be useful to ignore these exports. But on the flip side, someone using this package to find unused exports might expect to find the unnecessary exports as well. For that person, this behaviour change would mean they no longer can find a properly unused export.

The second (unrelated) feature request here is automatic fixing as requested by #23. It's a big enough undertaking and goes against the goal of this package to not modify the source repository in any way. The reason why this is a goal is that due to the limitation of the static analysis, it's impossible to be 100% confident that an import is in-fact, unused. Faulty logic in this package, faulty logic in a dependency, Typescript introducing new syntax would all spell disastrous outcomes for someone who doesn't use a version control properly. Therefore, going by the "first do no harm" principle, I'm not going to attempt it until Typescript supports proper static analysis.

**Comment by danvk** [comment]
> But I can see that it could be useful to ignore these exports. But on the flip side, someone using this package to find unused exports might expect to find the unnecessary exports as well. For that person, this behaviour change would mean they no longer can find a properly unused export.

@nadeesha are flags against your design goals for this tool? [That's a fine choice](http://neugierig.org/software/blog/2018/07/options.html) if they are. But this seems like the sort of dilemma that could be resolved by one.
