### ISSUE TITLE
[BUG] Ignore patterns does not work when symbol also has doccomment

### ISSUE THREAD

**Issue by torkelrogstad** [nadeesha/ts-prune#64]
Consider this: 

```ts
/**
 * Foo is foo
 */
// ts-prune-ignore-next
export const foo = 2
```

I'd expect `ts-prune` to not report on `foo`. However, I'm getting this output: 
```
src/foo.ts:7 - foo
```

This works, though: 
```
/**
 * Foo is foo
 * ts-prune-ignore-next
 */
export const foo = 2;
```

This is a bit unfortunate, because this causes `ts-prune-ignore-next` to show up in the hover tooltip in my IDE. I'd expect `ts-prune` to work the same way as `eslint`, where disable comments can be below doccomments, in the inline form. 

Thanks for creating a great tool!

**Comment by nadeesha** [comment]
Thanks for reporting this @torkelrogstad, and sorry, I've had to take some time off due to other commitments.

Much appreciated if you can look at this and consider contributing

This is the function that decides whether to ignore it or not: https://github.com/nadeesha/ts-prune/blob/4be7bcd15c1cd7d729305d0531c7d537d5bdedab/src/analyzer.ts#L68

I think printing out `possibleIgnoreLinePos` there would tell you where ts-prune is looking for the ignore comment.

**Comment by torkelrogstad** [comment]
#80 should do to the trick. Thanks for pointing me in the right direction!
