### ISSUE TITLE
[BUG] Misses mutually recursive dead imports

### ISSUE THREAD

**Issue by danvk** [nadeesha/ts-prune#97]
**Describe the bug**
It's possible for two modules to import symbols from one another but have both be unused if they just reference one another. In terms of the dependency graph, this would be an isolated loop.

**To Reproduce**

You can see this by creating these three files in the integration test:

```ts
// src/recursive/index.ts
import {nonrecAB} from './rec-a';

console.log(nonrecAB(10));
```

```ts
// src/recursive/rec-a.ts
import { b } from "../wildcard/b";
import { recB } from "./rec-b";

// This is dead but imported from rec-b.ts.
export const recA = (n: number): string[] => n === 0 ? [] : ['a', ...recB(n - 1)];

// This is alive (imported from index.ts).
export const nonrecAB = (n: number) => {
  const out = [];
  for (let i = 0; i < n; i++) {
    out.push(i ? 'b' : 'a');
  }
  return out;
};

export function reallydead() {}
```

```ts
// src/recursive/rec-b.ts
import { recA } from "./rec-a";

// This is dead but imported from rec-a.ts.
export const recB = (n: number): string[] => n === 0 ? [] : ['b', ...recA(n - 1)];
```

**Expected behavior**

When I run `yarn:test-integration`, I'd expect these three symbols to be reported as unused:

- `reallydead`
- `recA`
- `recB`

Instead, only `reallydead` is reported as unused.

**Optional: reference to the test project**

Here's a branch with the repro of the issue:
https://github.com/nadeesha/ts-prune/compare/master...danvk:mut-rec

**Comment by nadeesha** [comment]
Hi @danvk, due to the way the algorithm works, this cannot be supported easily without doing a major change. You can see if the mutual recursion is n-levels deep, (if we have rec-a..z) this eating up a lot of memory. This might also be the reason why typescript doesn't officially support this functionality OOTB.

IMHO there be a workaround to restructure ones code in a way that common code is refactored into its own file to avoid this issue. We'd have to rely on that for now, unfortunately.
